application: my-android-server
version: 2-0
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /webapp.txt
  static_files: webapp.txt
  upload: webapp\.txt

- url: /robots.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /image
  static_dir: image

- url: /favicon.ico
  static_files: image/favicon.ico
  upload: image/favicon\.ico

- url: /tasks/.*
  script: tasks.application

- url: /kyouen/.*
  script: kyouenserver.application

- url: /page/.*
  script: html.application

- url: /gcm/.*
  script: gcmserver.application

- url: /
  script: html.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: "1.6.1"
