application: my-android-server
version: 2-0
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /webapp.txt
  static_files: webapp.txt
  upload: webapp\.txt

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /image
  static_dir: image

- url: /favicon.ico
  static_files: image/favicon.ico
  upload: image/favicon\.ico

- url: /tasks/.*
  script: tasks.py

- url: /kyouen/.*
  script: kyouenserver.py

- url: /page/.*
  script: html.py

- url: /gcm/.*
  script: gcmserver.py

- url: /
  script: html.py

libraries:
- name: django
  version: "1.3"
- name: numpy
  version: "1.6.1"